/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppGoalSheetsIndexRouteImport } from './routes/app.goal-sheets.index'
import { Route as AppGoalSheetsSheetIdRouteImport } from './routes/app.goal-sheets.$sheetId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminUnlockRouteImport } from './routes/app.admin.unlock'
import { Route as AppAdminSharedGoalsRouteImport } from './routes/app.admin.shared-goals'
import { Route as AppAdminProgressRouteImport } from './routes/app.admin.progress'
import { Route as AppAdminEscalationsRouteImport } from './routes/app.admin.escalations'
import { Route as AppAdminCyclesRouteImport } from './routes/app.admin.cycles'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalSheetsIndexRoute = AppGoalSheetsIndexRouteImport.update({
  id: '/goal-sheets/',
  path: '/goal-sheets/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalSheetsSheetIdRoute = AppGoalSheetsSheetIdRouteImport.update({
  id: '/goal-sheets/$sheetId',
  path: '/goal-sheets/$sheetId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUnlockRoute = AppAdminUnlockRouteImport.update({
  id: '/admin/unlock',
  path: '/admin/unlock',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSharedGoalsRoute = AppAdminSharedGoalsRouteImport.update({
  id: '/admin/shared-goals',
  path: '/admin/shared-goals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProgressRoute = AppAdminProgressRouteImport.update({
  id: '/admin/progress',
  path: '/admin/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEscalationsRoute = AppAdminEscalationsRouteImport.update({
  id: '/admin/escalations',
  path: '/admin/escalations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCyclesRoute = AppAdminCyclesRouteImport.update({
  id: '/admin/cycles',
  path: '/admin/cycles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/cycles': typeof AppAdminCyclesRoute
  '/app/admin/escalations': typeof AppAdminEscalationsRoute
  '/app/admin/progress': typeof AppAdminProgressRoute
  '/app/admin/shared-goals': typeof AppAdminSharedGoalsRoute
  '/app/admin/unlock': typeof AppAdminUnlockRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/goal-sheets/$sheetId': typeof AppGoalSheetsSheetIdRoute
  '/app/goal-sheets/': typeof AppGoalSheetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/cycles': typeof AppAdminCyclesRoute
  '/app/admin/escalations': typeof AppAdminEscalationsRoute
  '/app/admin/progress': typeof AppAdminProgressRoute
  '/app/admin/shared-goals': typeof AppAdminSharedGoalsRoute
  '/app/admin/unlock': typeof AppAdminUnlockRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/goal-sheets/$sheetId': typeof AppGoalSheetsSheetIdRoute
  '/app/goal-sheets': typeof AppGoalSheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/cycles': typeof AppAdminCyclesRoute
  '/app/admin/escalations': typeof AppAdminEscalationsRoute
  '/app/admin/progress': typeof AppAdminProgressRoute
  '/app/admin/shared-goals': typeof AppAdminSharedGoalsRoute
  '/app/admin/unlock': typeof AppAdminUnlockRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/goal-sheets/$sheetId': typeof AppGoalSheetsSheetIdRoute
  '/app/goal-sheets/': typeof AppGoalSheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/achievements'
    | '/app/reports'
    | '/app/team'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/cycles'
    | '/app/admin/escalations'
    | '/app/admin/progress'
    | '/app/admin/shared-goals'
    | '/app/admin/unlock'
    | '/app/admin/users'
    | '/app/goal-sheets/$sheetId'
    | '/app/goal-sheets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/achievements'
    | '/app/reports'
    | '/app/team'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/cycles'
    | '/app/admin/escalations'
    | '/app/admin/progress'
    | '/app/admin/shared-goals'
    | '/app/admin/unlock'
    | '/app/admin/users'
    | '/app/goal-sheets/$sheetId'
    | '/app/goal-sheets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/achievements'
    | '/app/reports'
    | '/app/team'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/cycles'
    | '/app/admin/escalations'
    | '/app/admin/progress'
    | '/app/admin/shared-goals'
    | '/app/admin/unlock'
    | '/app/admin/users'
    | '/app/goal-sheets/$sheetId'
    | '/app/goal-sheets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goal-sheets/': {
      id: '/app/goal-sheets/'
      path: '/goal-sheets'
      fullPath: '/app/goal-sheets/'
      preLoaderRoute: typeof AppGoalSheetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goal-sheets/$sheetId': {
      id: '/app/goal-sheets/$sheetId'
      path: '/goal-sheets/$sheetId'
      fullPath: '/app/goal-sheets/$sheetId'
      preLoaderRoute: typeof AppGoalSheetsSheetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/unlock': {
      id: '/app/admin/unlock'
      path: '/admin/unlock'
      fullPath: '/app/admin/unlock'
      preLoaderRoute: typeof AppAdminUnlockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/shared-goals': {
      id: '/app/admin/shared-goals'
      path: '/admin/shared-goals'
      fullPath: '/app/admin/shared-goals'
      preLoaderRoute: typeof AppAdminSharedGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/progress': {
      id: '/app/admin/progress'
      path: '/admin/progress'
      fullPath: '/app/admin/progress'
      preLoaderRoute: typeof AppAdminProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/escalations': {
      id: '/app/admin/escalations'
      path: '/admin/escalations'
      fullPath: '/app/admin/escalations'
      preLoaderRoute: typeof AppAdminEscalationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/cycles': {
      id: '/app/admin/cycles'
      path: '/admin/cycles'
      fullPath: '/app/admin/cycles'
      preLoaderRoute: typeof AppAdminCyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCyclesRoute: typeof AppAdminCyclesRoute
  AppAdminEscalationsRoute: typeof AppAdminEscalationsRoute
  AppAdminProgressRoute: typeof AppAdminProgressRoute
  AppAdminSharedGoalsRoute: typeof AppAdminSharedGoalsRoute
  AppAdminUnlockRoute: typeof AppAdminUnlockRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppGoalSheetsSheetIdRoute: typeof AppGoalSheetsSheetIdRoute
  AppGoalSheetsIndexRoute: typeof AppGoalSheetsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCyclesRoute: AppAdminCyclesRoute,
  AppAdminEscalationsRoute: AppAdminEscalationsRoute,
  AppAdminProgressRoute: AppAdminProgressRoute,
  AppAdminSharedGoalsRoute: AppAdminSharedGoalsRoute,
  AppAdminUnlockRoute: AppAdminUnlockRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppGoalSheetsSheetIdRoute: AppGoalSheetsSheetIdRoute,
  AppGoalSheetsIndexRoute: AppGoalSheetsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
